# top-level

format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ ](bold green)$time
[â”‚](bold green)\
$hostname$localip$username$directory\
$git_branch$git_state$git_status$git_commit$git_metrics
[â”‚](bold green)\
$buf$c$cmake$cobol$crystal$dart$deno$dotnet$elixir$elm$erlang$golang$haskell\
$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$perl$php$purescript$python$red\
$rlang$ruby$rust$scala$swift$terraform$vagrant$vlang$zig\
$docker_context$package$shlvl$memory_usage$sudo$status$battery\
$status$container$shell
[â”” ](bold green)$character
"""

[cmd_duration]
disabled = false
format = "( [$duration]($style))"

[directory]
format = "( [$path]($style)[$read_only]($read_only_style))"
repo_root_format = "( [$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style))"
repo_root_style = "bold cyan"
style = "cyan"
truncation_length = 8
truncation_symbol = ".../"

[docker_context]
format = "( [$symbol$context]($style))"

# language-specific
[elm]
format = "( [$symbol$version]($style))"
style = "cyan"
version_format = "$raw"

[git_branch]
format = "( [$symbol$branch(:$remote_branch)]($style))"

[git_commit]
format = "( [$hash$tag]($style))"

[git_metrics]
disabled = false
format = "( [+$added]($added_style)[-$deleted]($deleted_style))"

[git_state]
format = "( [$state:($progress_current/$progress_total)]($style))"

[git_status]
format = "( [$conflicted]($style))( [$ahead]($style))( [$behind]($style))( [$diverged]($style))( [$up_to_date]($style))( [$untracked]($style))( [$stashed]($style))( [$modified]($style))( [$staged]($style))( [$renamed]($style))( [$deleted]($style))"
ignore_submodules = true

[golang]
format = "( [$symbol$version]($style))"
style = "cyan"
version_format = "$raw"

[haskell]
format = "( [$symbol$version]($style))"
style = "purple"
version_format = "$raw"

[hostname]
format = "( [$ssh_symbol$hostname]($style))"
ssh_only = false
ssh_symbol = "ğŸŒ"

[julia]
format = "( [$symbol$version]($style))"
style = "purple"
version_format = "$raw"

[kotlin]
format = "( [$symbol$version]($style))"
style = "blue"
version_format = "$raw"

[localip]
disabled = false
format = "( [$localipv4]($style))"
ssh_only = true
style = "green"

[lua]
format = "( [$symbol$version]($style))"
style = "blue"
version_format = "$raw"

[memory_usage]
disabled = false
format = "( [$symbol$ram(|$swap)]($style))"

[nodejs]
disabled = true
format = "( [$symbol$version]($style))"
style = "green"
version_format = "$raw"

[os]
disabled = false

[package]
format = "( [$symbol$version]($style))"
version_format = "$raw"

[python]
format = "( [$symbol$version]($style))"
style = "yellow"
version_format = "$raw"

[rust]
format = "( [$symbol$version]($style))"
style = "red"
version_format = "$raw"

[shlvl]
disabled = false
format = "( [$symbol  $shlvl]($style))"
repeat = true
symbol = "â†•ï¸"
threshold = 3

[sudo]
disabled = true
format = "( [$symbol]($style))"

[time]
disabled = false
format = "[$time]($style)"  # special format
time_format = "%Y-%m-%d %H:%M:%S"

[username]
format = "( [$user]($style))"
show_always = true
